ALTER TABLE stories
    ADD COLUMN IF NOT EXISTS timeline_branch_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS timeline_split_date TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS timeline_split_unknown BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS timeline_merge_date TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS timeline_merge_unknown BOOLEAN NOT NULL DEFAULT FALSE;
